version: '2'
services:
  web1:
    build: web1/

  web2:
    build: web2/

  php52:
    build: php52/

  php70:
    build: php70/

  nginx:
    build: nginx/
    ports:
      - "80:80"